let GameDB = {
    version: 3,
    bugs: {
        destruction: false,
        wonderous: false,
        swarm: false,
        mission3: false,
        construction: false
    },
    academy: {
        getCampaignAP(campaigns) {
            let bonus = 1;
            if (campaigns >= 3) bonus *= 1.1;
            if (campaigns >= 7) bonus *= 1.2;
            if (campaigns >= 11) bonus *= 1.25;
            if (campaigns >= 15) bonus *= 1.5;
            if (campaigns >= 19) bonus *= 1.5;
            if (campaigns >= 23) bonus *= 2;
            return bonus;
        },
        personnel: ['pods','fireteams','titans','corvettes'],
        planets: 6,
        farms: [
            {
                id: 11,
                baseTime: 30,
                maxPop: 20,
                baseAP: 2,
                baseMats: [38,0,0,0,0,0,0,0]
            },
            {
                id: 12,
                baseTime: 360,
                maxPop: 60,
                baseAP: 64,
                baseMats: [0,320,0,0,0,0,0,0]
            },
            {
                id: 13,
                baseTime: 2400,
                maxPop: 100,
                baseAP: 500,
                baseMats: [1350,280,760,0,0,0,0,0]
            },
            {
                id: 21,
                baseTime: 150,
                maxPop: 80,
                baseAP: 14,
                baseMats: [0,0,0,20,0,0,0,0]
            },
            {
                id: 22,
                baseTime: 2400,
                maxPop: 160,
                baseAP: 75,
                baseMats: [0,0,560,0,80,0,0,0]
            },
            {
                id: 23,
                baseTime: 72000,
                maxPop: 500,
                baseAP: 4864,
                baseMats: [0,0,0,2200,320,260,0,0]
            },
            {
                id: 31,
                baseTime: 3000,
                maxPop: 150,
                baseAP: 840,
                baseMats: [0,0,0,0,0,0,19,0]
            },
            {
                id: 32,
                baseTime: 975000,
                maxPop: 2000,
                baseAP: 422000,
                baseMats: [0,0,0,0,0,0,0,80]
            },
            {
                id: 33,
                baseTime: 1875000,
                maxPop: 4000,
                baseAP: 845000,
                baseMats: [0,0,0,0,5200,2440,3980,160]
            }
        ],
        projects: [
            {
                name: 'Storage Facility',
                baseCosts: [600,200,0,0,0,0,0,0],
                scalar: 1.25,
                bump: 0.016
            },
            {
                name: 'Transfer Wires',
                baseCosts: [2750,1500,500,0,0,0,0,0],
                scalar: 1.4,
                bump: 0.05
            },
            {
                name: 'Bio-Mechanics Lab',
                basecosts : [0,0,2400,1000,500,0,0,0],
                scalar: 1.7,
                bump: 0.09
            },
            {
                name: 'Exo-Energy',
                baseCosts: [0,7000,5000,1500,1500,0,0,0],
                scalar: 1.4,
                bump: 0.07
            },
            {
                name: 'Defensive Research',
                baseCosts: [0,0,0,0,0,1000,200,0],
                scalar: 1.6,
                bump: 0.08
            },
            {
                name: 'Warp-Drive Lab',
                baseCosts: [0,0,0,0,260000,120000,28000,28000],
                scalar: 2,
                bump: 0.11
            },
            {
                name: 'Fuel Compression',
                baseCosts: [1e38,0,0,4e37,0,0,7e36,0],
                scalar: 3,
                bump: 0.13
            },
            {
                name: 'Quantum Weaponry',
                baseCosts: [0,2e45,0,0,5e44,0,0,0],
                scalar: 3.2,
                bump: 0.16
            },
            {
                name: 'Robo-Douglett',
                baseCosts: [0,0,3e53,0,0,6e52,0,8e51],
                scalar: 12,
                bump: 0.19
            }
        ],
        projectNextLevelCost(projectID,level,costDiv) {
            let project = this.projects[projectID];
            return project.baseCosts.map(mat => mat * Math.pow(project.scalar + (project.bump * Math.floor(level / 100)), level) / costDiv);
        }
    },
    ships: {
        cradle: {
            evoPows: [],
            rankReqs: []
        },
        auxesia: {
            evoPows: [],
            rankReqs: []
        },
        zagreus: {
            evoPows: [],
            rankReqs: []
        },
        hephaestus: {
            evoPows: [],
            rankReqs: []
        },
        demeter: {
            evoPows: [],
            rankReqs: []
        },
        koios: {
            evoPows: [],
            rankReqs: []
        },
        zeus: {
            evoPows: [1,2,4,12,48],
            rankReqs: [] // TODO: get func for rank req calc
        },
        ouroboros: {
            evoPows: [],
            rankReqs: []
        }
    },
    tokens: {
            TOKEN1: {
                i: 0,
                name: 'Tokens Boost',
                cat: 1,
                cost: 20,
                scalar: 5,
                max: 20,
                unlock: 'MK2',
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            DIAMOND: {
                i: 1,
                name: 'Diamonds Boost',
                cat: 1,
                cost: 200,
                scalar: 300,
                max: 2,
                unlock: 'MK2',
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            CELLS: {
                i: 2,
                name: "Cells Boost",
                cat: 1,
                cost: 1,
                scalar: 0.25,
                max: 60,
                unlock: 'MK2',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MODS: {
                i: 3,
                name: "Mod Points Boost",
                cat: 1,
                cost: 10,
                scalar: 2,
                max: 200,
                unlock: "Zagreus",
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1.01,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK1: {
                i: 4,
                name: "MK1 Gen Boost",
                cat: 1,
                cost: 1,
                scalar: 0.1,
                max: 5000,
                unlock: 'MK1',
                bonus: {
                    MK1: 1.01,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK2: {
                i: 5,
                name: "MK2 Gen Boost",
                cat: 1,
                cost: 2,
                scalar: 0.12,
                max: 5000,
                unlock: 'MK2',
                bonus: {
                    MK1: 1,
                    MK2: 1.01,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK3: {
                i: 6,
                name: "MK3 Gen Boost",
                cat: 1,
                cost: 3,
                scalar: 0.13,
                max: 5000,
                unlock: 'MK3',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1.01,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK4: {
                i: 7,
                name: "MK4 Gen Boost",
                cat: 1,
                cost: 4,
                scalar: 0.14,
                max: 5000,
                unlock: 'MK4',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1.01,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK5: {
                i: 8,
                name: "MK5 Gen Boost",
                cat: 1,
                cost: 15,
                scalar: 0.15,
                max: 5000,
                unlock: 'MK5',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1.01,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK6: {
                i: 9,
                name: "MK6 Gen Boost",
                cat: 1,
                cost: 26,
                scalar: 0.16,
                max: 5000,
                unlock: 'MK6',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1.01,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK7: {
                i: 10,
                name: "MK7 Gen Boost",
                cat: 1,
                cost: 37,
                scalar: 0.2,
                max: 5000,
                unlock: 'MK7',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1.01,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK8: {
                i: 11,
                name: "MK8 Gen Boost",
                cat: 1,
                cost: 48,
                scalar: 0.3,
                max: 5000,
                unlock: 'MK8',
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1.01,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            TOKEN2: {
                i: 0,
                name: "Tokens Boost",
                cat: 2,
                cost: 1000,
                scalar: 500,
                max: 10,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            DAILY1: {
                i: 1,
                name: "Daily Tokens",
                cat: 2,
                cost: 1000,
                scalar: 800,
                max: 10,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            MPSH: {
                i: 2,
                name: "Mod Points + Shards",
                cat: 2,
                cost: 1275,
                scalar: 25,
                max: 500,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1.02,
                    SHARDS: 1.02,
                    RP: 1,
                    AP: 1
                }
            },
            MK1MK2: {
                i: 3,
                name: "MK1 + MK2",
                cat: 2,
                cost: 75,
                scalar: 2,
                max: 2500,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 1.02,
                    MK2: 1.02,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK3MK4: {
                i: 4,
                name: "MK3 + MK4",
                cat: 2,
                cost: 100,
                scalar: 3,
                max: 2500,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1.02,
                    MK4: 1.02,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK5MK6: {
                i: 5,
                name: "MK5 + MK6",
                cat: 2,
                cost: 125,
                scalar: 4,
                max: 2500,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1.02,
                    MK6: 1.02,
                    MK7: 1,
                    MK8: 1,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            MK7MK8: {
                i: 6,
                name: "MK7 + MK8",
                cat: 2,
                cost: 150,
                scalar: 5,
                max: 2500,
                unlock: "TokensTier1",
                bonus: {
                    MK1: 1,
                    MK2: 1,
                    MK3: 1,
                    MK4: 1,
                    MK5: 1,
                    MK6: 1,
                    MK7: 1.02,
                    MK8: 1.02,
                    MP: 1,
                    SHARDS: 1,
                    RP: 1,
                    AP: 1
                }
            },
            TOKEN3: {
                i: 0,
                name: "Tokens Boost",
                cat: 3,
                cost: 2500,
                scalar: 750,
                max: 25,
                unlock: "TokensTier2",
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            DAILY2: {
                i: 1,
                name: "Daily Tokens",
                cat: 3,
                cost: 3000,
                scalar: 900,
                max: 50,
                unlock: "TokensTier2",
                bonus: {
                    MK1: 2,
                    MK2: 2,
                    MK3: 2,
                    MK4: 2,
                    MK5: 2,
                    MK6: 2,
                    MK7: 2,
                    MK8: 2,
                    MP: 2,
                    SHARDS: 2,
                    RP: 2,
                    AP: 2
                }
            },
            GMPRP: {
                i: 2,
                name: "All Gens + MP + RP Boost",
                cat: 3,
                cost: 7000,
                scalar: 100,
                max: 2000,
                unlock: "TokensTier2",
                bonus: {
                    MK1: 1.03,
                    MK2: 1.03,
                    MK3: 1.03,
                    MK4: 1.03,
                    MK5: 1.03,
                    MK6: 1.03,
                    MK7: 1.03,
                    MK8: 1.03,
                    MP: 1.03,
                    SHARDS: 1,
                    RP: 1.03,
                    AP: 1
                }
            },
            GSHAP: {
                i: 3,
                name: "All Gens + Shards + AP Boost",
                cat: 3,
                cost: 8000,
                scalar: 200,
                max: 2000,
                unlock: "TokensTier2",
                bonus: {
                    MK1: 1.03,
                    MK2: 1.03,
                    MK3: 1.03,
                    MK4: 1.03,
                    MK5: 1.03,
                    MK6: 1.03,
                    MK7: 1.03,
                    MK8: 1.03,
                    MP: 1,
                    SHARDS: 1.03,
                    RP: 1,
                    AP: 1.03
                }
            }
    },
    diamonds: {
        MK1: {
            name: "MK1 Gen Boost",
            cat: "GENERATOR",
            cost: 10,
            scalar: 1,
            max: 100,
            unlock: "MK1",
            bonus: {
                CELL: 1,
                MK1: 1.01,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK2: {
            name: "MK2 Gen Boost",
            cat: "GENERATOR",
            cost: 20,
            scalar: 2,
            max: 100,
            unlock: "MK2",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1.02,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK3: {
            name: "MK3 Gen Boost",
            cat: "GENERATOR",
            cost: 30,
            scalar: 3,
            max: 100,
            unlock: "MK3",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1.03,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK4: {
            name: "MK4 Gen Boost",
            cat: "GENERATOR",
            cost: 40,
            scalar: 4,
            max: 100,
            unlock: "MK4",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1.04,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK5: {
            name: "MK5 Gen Boost",
            cat: "GENERATOR",
            cost: 50,
            scalar: 5,
            max: 100,
            unlock: "MK5",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1.05,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK6: {
            name: "MK6 Gen Boost",
            cat: "GENERATOR",
            cost: 60,
            scalar: 6,
            max: 100,
            unlock: "MK6",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1.06,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK7: {
            name: "MK7 Gen Boost",
            cat: "GENERATOR",
            cost: 70,
            scalar: 7,
            max: 100,
            unlock: "MK7",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1.07,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MK8: {
            name: "MK8 Gen Boost",
            cat: "GENERATOR",
            cost: 80,
            scalar: 8,
            max: 100,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1.08,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        TOKENS: {
            name: "Tokens Boost",
            cat: "SPECIAL",
            cost: 100,
            scalar: 200,
            max: 6,
            unlock: "MK2",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        CELLS: {
            name: "Cells Boost",
            cat: "SPECIAL",
            cost: 200,
            scalar: 1,
            max: 1000,
            unlock: "MK2",
            bonus: {
                CELL: 1.25,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MODS: {
            name: "Mod Points Boost",
            cat: "SPECIAL",
            cost: 300,
            scalar: 10,
            max: 30,
            unlock: "Zagreus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.07,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        SHARDS: {
            name: "Shards Boost",
            cat: "SPECIAL",
            cost: 400,
            scalar: 20,
            max: 30,
            unlock: "Demeter",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1.07,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        RESEARCH: {
            name: "Research Points Boost",
            cat: "SPECIAL",
            cost: 500,
            scalar: 25,
            max: 30,
            unlock: "Koios",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1.1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        ACADEMY: {
            name: "Academy Boost",
            cat: "SPECIAL",
            cost: 600,
            scalar: 30,
            max: 30,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1.05,
                MATS: 1,
                MISSIONS: 1
            }
        },
        ALLGENS: {
            name: "All Gens Boost",
            cat: "SPECIAL",
            cost: 700,
            scalar: 35,
            max: 30,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1.15,
                MK2: 1.15,
                MK3: 1.15,
                MK4: 1.15,
                MK5: 1.15,
                MK6: 1.15,
                MK7: 1.15,
                MK8: 1.15,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MATS: {
            name: "Mats Boost",
            cat: "SPECIAL",
            cost: 700,
            scalar: 25,
            max: 30,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1.05,
                MISSIONS: 1
            }
        },
        ALPHA: {
            name: "Alpha Card",
            cat: "ONETIMER",
            cost: 1000,
            scalar: 0,
            max: 1,
            unlock: "MK2",
            bonus: {
                CELL: 1.3,
                MK1: 1.78,
                MK2: 1.54,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        BETA: {
            name: "Beta Card",
            cat: "ONETIMER",
            cost: 1000,
            scalar: 0,
            max: 1,
            unlock: "MK3",
            bonus: {
                CELL: 1,
                MK1: 1.54,
                MK2: 1.54,
                MK3: 1.54,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        CETI: {
            name: "Ceti Card",
            cat: "ONETIMER",
            cost: 1000,
            scalar: 0,
            max: 1,
            unlock: "MK3",
            bonus: {
                CELL: 1.24,
                MK1: 1,
                MK2: 1,
                MK3: 1.32,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.08,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        DELTA: {
            name: "Delta Card",
            cat: "ONETIMER",
            cost: 1500,
            scalar: 0,
            max: 1,
            unlock: "MK3",
            bonus: {
                CELL: 2.3,
                MK1: 1,
                MK2: 1.14,
                MK3: 1.14,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        EPSILON: {
            name: "Epsilon Card",
            cat: "ONETIMER",
            cost: 1500,
            scalar: 0,
            max: 1,
            unlock: "MK4",
            bonus: {
                CELL: 1,
                MK1: 1.52,
                MK2: 1.52,
                MK3: 1,
                MK4: 1.44,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        FENIX: {
            name: "Fenix Card",
            cat: "ONETIMER",
            cost: 1500,
            scalar: 0,
            max: 1,
            unlock: "MK4",
            bonus: {
                CELL: 1.16,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1.5,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.07,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        GAMMA: {
            name: "Gamma Card",
            cat: "ONETIMER",
            cost: 2000,
            scalar: 0,
            max: 1,
            unlock: "MK5",
            bonus: {
                CELL: 2.4,
                MK1: 1,
                MK2: 1,
                MK3: 1.34,
                MK4: 1,
                MK5: 1.34,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        HELION: {
            name: "Helion Card",
            cat: "ONETIMER",
            cost: 2000,
            scalar: 0,
            max: 1,
            unlock: "MK2",
            bonus: {
                CELL: 1,
                MK1: 1.68,
                MK2: 1.68,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.13,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        IXION: {
            name: "Ixion Card",
            cat: "ONETIMER",
            cost: 2000,
            scalar: 0,
            max: 1,
            unlock: "MK5",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1.64,
                MK5: 1.52,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.16,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        JUNO: {
            name: "Juno Card",
            cat: "ONETIMER",
            cost: 2500,
            scalar: 0,
            max: 1,
            unlock: "Demeter",
            bonus: {
                CELL: 1.65,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.25,
                SHARDS: 1.45,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        KAPPA: {
            name: "Kappa Card",
            cat: "ONETIMER",
            cost: 2500,
            scalar: 0,
            max: 1,
            unlock: "MK6",
            bonus: {
                CELL: 1,
                MK1: 2.84,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1.92,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.4,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        LYRA: {
            name: "Lyra Card",
            cat: "ONETIMER",
            cost: 2500,
            scalar: 0,
            max: 1,
            unlock: "Demeter",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 2.16,
                MK3: 1,
                MK4: 1,
                MK5: 2.12,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1.5,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        MIKO: {
            name: "Miko Card",
            cat: "ONETIMER",
            cost: 3000,
            scalar: 0,
            max: 1,
            unlock: "MK7",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 3,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.32,
                SHARDS: 1,
                OPS: 1,
                RP: 1.34,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        NORA: {
            name: "Nora Card",
            cat: "ONETIMER",
            cost: 3000,
            scalar: 0,
            max: 1,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 2.08,
                MK7: 1.71,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1.23,
                MATS: 1,
                MISSIONS: 1
            }
        },
        OMEGA: {
            name: "Omega Card",
            cat: "ONETIMER",
            cost: 3000,
            scalar: 0,
            max: 1,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.1,
                SHARDS: 1.42,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1.4,
                MATS: 1,
                MISSIONS: 1
            }
        },
        PEGASUS: {
            name: "Pegasus Card",
            cat: "ONETIMER",
            cost: 3500,
            scalar: 0,
            max: 1,
            unlock: "MK8",
            bonus: {
                CELL: 5.5,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 2.8,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1.5,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        QORU: {
            name: "Qoru Card",
            cat: "ONETIMER",
            cost: 3500,
            scalar: 0,
            max: 1,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 4.9,
                MK7: 3.6,
                MK8: 2.2,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        RIGEL: {
            name: "Rigel Card",
            cat: "ONETIMER",
            cost: 3500,
            scalar: 0,
            max: 1,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1.62,
                OPS: 1,
                RP: 1.46,
                STUDIES: 1,
                AP: 1.15,
                MATS: 1,
                MISSIONS: 1
            }
        },
        SIGMA: {
            name: "Sigma Card",
            cat: "ONETIMER",
            cost: 4000,
            scalar: 0,
            max: 1,
            unlock: "MK7",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 4.4,
                MK5: 1,
                MK6: 1,
                MK7: 3.8,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.75,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        TYPHON: {
            name: "Typhon Card",
            cat: "ONETIMER",
            cost: 4000,
            scalar: 0,
            max: 1,
            unlock: "Koios",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 5.46,
                MK4: 1,
                MK5: 1,
                MK6: 2.44,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 2,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        UTOPIA: {
            name: "Utopia Card",
            cat: "ONETIMER",
            cost: 4000,
            scalar: 0,
            max: 1,
            unlock: "Zeus",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 3.88,
                MK5: 3.44,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1.2,
                MATS: 1,
                MISSIONS: 1
            }
        },
        VEX: {
            name: "Vex Card",
            cat: "ONETIMER",
            cost: 4500,
            scalar: 0,
            max: 1,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 4,
                SW: 1,
                HW: 1,
                MP: 2.2,
                SHARDS: 1.7,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        XENO: {
            name: "Xeno Card",
            cat: "ONETIMER",
            cost: 4500,
            scalar: 0,
            max: 1,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 4,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1.9,
                OPS: 1,
                RP: 2.8,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        ZION: {
            name: "Zion Card",
            cat: "ONETIMER",
            cost: 4500,
            scalar: 0,
            max: 1,
            unlock: "MK8",
            bonus: {
                CELL: 1,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 4,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1.95,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1.1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        ANDROMEDA: {
            name: "Andromeda Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 2.33,
                MK1: 6.05,
                MK2: 4.19,
                MK3: 1,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1.5,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        BEERUS: {
            name: "Beerus Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 1,
                MK1: 4.19,
                MK2: 4.19,
                MK3: 4.19,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1.5,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        CENTURION: {
            name: "Centurion Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 1.63,
                MK1: 1,
                MK2: 1,
                MK3: 4.75,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 2.15,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        DAHL: {
            name: "Dahl Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 5.24,
                MK1: 1,
                MK2: 2.12,
                MK3: 3.2,
                MK4: 1,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1.2,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        ELYSIUM: {
            name: "Elysium Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 6.33,
                MK1: 1,
                MK2: 2.05,
                MK3: 1,
                MK4: 4.5,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1,
                SHARDS: 1,
                OPS: 1.2,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1
            }
        },
        FERRICK: {
            name: "Ferrick Card",
            cat: "LARGEONETIMER",
            cost: 5000,
            scalar: 0,
            max: 1,
            unlock: "DiamondOneTimer",
            bonus: {
                CELL: 4.19,
                MK1: 1,
                MK2: 1,
                MK3: 1,
                MK4: 2.33,
                MK5: 1,
                MK6: 1,
                MK7: 1,
                MK8: 1,
                SW: 1,
                HW: 1,
                MP: 1.95,
                SHARDS: 1,
                OPS: 1,
                RP: 1,
                STUDIES: 1,
                AP: 1,
                MATS: 1,
                MISSIONS: 1.2
            }
        }
    },
    mods: {}
};

const suffixes = {
    k: 1e3,
    m: 1e6,
    b: 1e9,
    t: 1e12,
    qa: 1e15,
    qu: 1e18,
    sx: 1e21,
    sp: 1e24,
    o: 1e27,
    n: 1e30,
    d: 1e33
}

/**
 * @param {string} val 
 */
function getNumFromShort(val) {
    return parseFloat(val.slice(0,val.indexOf(val.match(`/${Object.keys(suffixes).join("|")}/`))));
}

/**
 * @param {string} val 
 */
function getSufFromShort(val) {
    return val.slice(val.indexOf(val.match(`/${Object.keys(suffixes).join("|")}/`)));
}

/**
 * @param {string} val 
 */
function parseShortNum(val) {
    if (!isFormattedShortNum(val))
        throw Error("`val` IS NOT IN SHORT FORMAT; CANNOT PARSE");
    let num = getNumFromShort(val);
    let suffix = getSufFromShort(val);
    return num * suffixes[suffix];
}

/**
 * @param {string} val 
 */
function parseExpNum(val) {
    const x = val.split('e');
    if (x.length == 2) {
        return parseFloat(n) * Math.pow(10,parseFloat(e));
    }
}

function isFormattedExpNum(input) {
    return typeof input == 'string' && input.match(/^(\d+\.?\d*e*\d+)/)
}

function isFormattedShortNum(input) {
    return typeof input == 'string' && input.match(/(k|m|b|t|qa|qu|sx|sp|o|n|d)$/);
}

/**
 * @param {string|number} input 
 */
function isNum(input) {
    return typeof input == 'number' || isFormattedExpNum(input) || isFormattedShortNum(input);
}

/**
 * @param {number} val 
 * @param {'exp'|'short'} type 
 */
function formatNumber(val, type) {
    if (type == 'exp') {
        return val.toExponential(2);
    }
    if (type == 'short') {
        
    }
}